export class ReasonAlreadyExistsException extends Error {
    constructor(descripcion: string) {
      super(`Ya existe un motivo con la descripci√≥n: "${descripcion}"`);
      this.name = 'ReasonAlreadyExistsException';
    }
  }